# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Weiguo Zhou(周卫国)
tagline:          'Happy coding, happy blogging.'
description:      'Start here,<br>make a difference.'
url:              http://www.wangzerui.com
baseurl:          /

author:
  name:           'Weiguo Zhou(周卫国)'
  email:          weiguochow@gmail.com

paginate:         2

gems: [jekyll-paginate]

# custom vars
google_analytics: UA-63207330-1
emailme:          mailto:weiguochow@gmail.com
github:
  repo:           https://github.com/weiguochow.github.io/
version:          Mar.04.2017
github_username:  weiguochow
facebook_username: zrwang.cuhk
linkedin_username: zrwang
twitter_username: wangzerui
# google_plus_username: 
# instagram_username: wzr.mavericker

